name: CI
on: [push]
env:
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
  TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PMET-public/action-keep-GH-active@master
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master
